config/routes.rb
Rails.application.routes.draw do
  
  resources :admin_users do 
    member do 
      get 'delete'
    end
  end
  

  root 'demo#index'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  
  resources :subjects do 
    member do 
      get 'delete'
    end
  end
  
  resources :pages do 
    member do 
      get 'delete'
    end
  end
  
  resources :sections do 
    member do 
      get 'delete'
    end
  end

   
   get 'demo/hello'

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout 'admin'

  #before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  # doesn't run before the "except" actions
   before_action :confirm_login, :except => [:login, :attempt_login, :logout]
   
  def menu
    # display text & links
  end

  def login
    # login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username]).first
      if found_user
        found_user.authenticate(params[:password_digest])
        authorized_user = found_user
      end
    end
      if authorized_user
        session[:user_id] = authorized_user.id 
        flash[:notice] = "You Are logged In"
        redirect_to admin_path
      else
        flash.now[:notice] = "Invalid Username or password"
        render 'login'
      end
    end
  

  def logout
    # mark user as logged out
    session[:user_id] = nil
    flash[:notice]= "You Are logged out"
    redirect_to access_login_path
  end
  
  private
  def admin_params
    params.require(:admin_user).permit(:first_name, :last_name, :email, :username, :password)
  end
  
end  

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
  <table>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= text_field_tag(:username) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In") %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class="identity">Logged in as: <%= session[:username] %></div>
  <ul>
    <li><%= link_to("Manage Subjects", subjects_path) %></li>
    <li><%= link_to("Manage Pages", pages_path) %></li>
    <li><%= link_to("Manage Sections", sections_path) %></li>
    <li><%= link_to("Manage Admin Users", admin_users_path) %></li>
    <li><%= link_to("Logout", access_logout_path) %></li>
  </ul>
</div>