config/routes.rb
Rails.application.routes.draw do
  
  resources :admin_users do 
    member do 
      get 'delete'
    end
  end
  

  root 'demo#index'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  
  resources :subjects do 
    member do 
      get 'delete'
    end
  end
  
  resources :pages do 
    member do 
      get 'delete'
    end
  end
  
  resources :sections do 
    member do 
      get 'delete'
    end
  end

   
   get 'demo/hello'

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :page
  has_many :section_edits
  has_many :admin_users, :through => :section_edits
  
  
  CONTENT_TYPES = ['text', 'HTML']

  validates_presence_of :name
  validates_length_of :name, :maximum => 255
  validates_inclusion_of :content_type, :in => CONTENT_TYPES,
    :message => "must be one of: #{CONTENT_TYPES.join(', ')}"
  validates_presence_of :content

  
  #scopes
  scope :visible, -> {where(:visible => true)}
  scope :invisible, -> {where(:postion => false)}
  scope :sorted, -> {order("position ASC")}
  scope :newest_first, -> {order("created_at DESC")}
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
   before_action :confirm_login
  layout 'admin'
  
  def index
    @sections = Section.sorted
    
  end

  def new
    @section = Section.new 
    @section_count = Section.count + 1
    @pages = Page.sorted
  end
  
  def create
    @section = Section.new(sections_params)
    if @section.save
      redirect_to sections_path
    else
      @section_count = Section.count + 1
      @pages = Page.sorted
      render 'new'
    end
    
  end

  def show
    @section = Section.find(params[:id])
  end
  
  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
    @pages = Page.sorted
  end
  
  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(sections_params)
      redirect_to section_path(@section)
    else
    @section_count = Section.count
    @pages = Page.sorted
      render 'edit'
    end
  end
  
  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
    
  end
  
  def delete
    @section = Section.find(params[:id])
  end
  
  
  
  private 
   def sections_params
     params.require(:section).permit(:name, :position, :content_type, :content, :visible)
   end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<div class="sections new">
  <h2>Create section</h2>

  <%= form_for(@section) do |f| %>
<%= error_messages_for(f.object) %>
<table summary="section form fields">
  <tr>
    <th><%= f.label(:name) %></th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Page</th>
    <td><%= f.select(:page_id, @pages.map{|s| [s.name, s.id]}) %></td>
  </tr>
  <tr>
    <th><%= f.label(:position) %></th>
    <td><%= f.select(:position, 1..@section_count) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible) %></th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th><%= f.label(:content_type) %></th>
    <td><%= f.radio_button(:content_type, 'text') %> Text
    <td><%= f.radio_button(:content_type, 'HTML') %> HTML</td>
  </tr>
  <tr>
    <th><%= f.label(:content) %></th>
    <td><%= f.text_area(:content, :size => '40x10') %></td>
  </tr>
  <tr>
      <div class = "form-button">
      <%= f.submit "Create section" %>
  </div>
  </tr>
  </table>
  

  <% end %>
</div>

app/views/sections/delete.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>
<%= :notice %>
<div class="sections delete">
  <h2>Delete section</h2>

  <%= form_for(@section, method: :delete) do |f| %>

    <p>Are you sure you want to permanently delete this section?</p>

    <p class="reference-name"><%= @section.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete section") %>
    </div>

  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<%= render 'form' %>

app/views/sections/index.html.erb
<div class="sections index">
 <h2>sections </h2></br>

  <%= link_to "Add New section", new_section_path %>
  

  <div><%= pluralize(@sections.size, 'section') %> found</div>
  <table class="listing" summary="section list">
    <tr class="header">
      <th>Position </th>
      <th>section</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @sections.each do |section| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td><%= section.position %></td>
      <td><%= section.name %></td>
      <td class="center"><%= status_tag(section.visible) %></td>
      <td class="actions">
        <%= link_to("View sections", {:controller => 'sections', :section_id => section.id}, :class => 'action show') %>
        <%= link_to("Show", section_path(section), :class => 'action show') %>
        <%= link_to("Edit", {:action => 'edit', :id => section.id}, :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
  
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<%= render 'form' %>

app/views/sections/show.html.erb
<div class="sections show">
  <h2>Show section</h2>

  <table summary="section detail view">
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Content Type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content </th>
      <td><%= @section.content %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>

</div>