config/routes.rb
Rails.application.routes.draw do
  
  resources :admin_users do 
    member do 
      get 'delete'
    end
  end
  

  root 'demo#index'
  
  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  
  resources :subjects do 
    member do 
      get 'delete'
    end
  end
  
  resources :pages do 
    member do 
      get 'delete'
    end
  end
  
  resources :sections do 
    member do 
      get 'delete'
    end
  end

   
   get 'demo/hello'

end

app/views/pages/_form.html.erb
<div class="pages new">
  <h2>Create page</h2>

  <%= form_for(@page) do |f| %>
   <%= error_messages_for(f.object) %>
    <table summary="page form fields">
  <tr>
    <th><%= f.label(:name) %></th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Subject ID</th>
    <td><%= f.select(:subject_id, @subjects.map{|s| [s.name, s.id]}) %></td>
  </tr>
  <tr>
    <th><%= f.label(:position) %></th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr>
    <th><%= f.label(:permalink) %></th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible) %></th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  </table>
  <div class = "form-button">
      <%= f.submit "Create page" %>
  </div>

  <% end %>
</div>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>
<%= :notice %>
<div class="pages delete">
  <h2>Delete page</h2>

  <%= form_for(@page, method: :delete) do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>

    <p class="reference-name"><%= @page.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<%= render 'form' %>

app/views/pages/index.html.erb
<div class="pages index">
 <h2>pages </h2></br>
 <%= @count %>
 

  <%= link_to "Add New page", new_page_path %>
  

  <div><%= pluralize(@pages.size, 'page') %> found</div>
  <table class="listing" summary="page list">
    <tr class="header">
      <th>Position </th>
      <th>page</th>
      <th>Visible</th>
      <th>Permalink</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td><%= page.position %></td>
      <td><%= page.name %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"><%=  page.permalink %></td>
      <td class="actions">
        <%= link_to("View Pages", {:controller => 'pages', :page_id => page.id}, :class => 'action show') %>
        <%= link_to("Show", page_path(page), :class => 'action show') %>
        <%= link_to("Edit", {:action => 'edit', :id => page.id}, :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
  
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<%= render 'form' %>

app/views/pages/show.html.erb
<div class="pages show">
  <h2>Show page</h2>

  <table summary="page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>